language: python
dist: trusty
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - docker
before_script:
  # @see https://medium.com/@mtparet/install-mysql-server-5-7-on-travis-96f2ebc0f339
  # @see https://hub.docker.com/_/mysql/
  - sudo service mysql stop  # stop any running MySQL server
  - sudo docker run -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d -p 127.0.0.1:3306:3306 mysql:5.7
  - sleep 2 # wait for MySQL server to be fully set up
  - sudo docker ps
  # set up a database
  - mysql -h127.0.0.1 -u root -e "CREATE DATABASE index_digest;"
  - mysql -h127.0.0.1 -u root -e "CREATE USER 'index_digest'@'0.0.0.0' IDENTIFIED BY 'qwerty';"
  - mysql -h127.0.0.1 -u root -e "GRANT ALL ON index_digest.* TO 'index_digest'@'0.0.0.0';"
  - "./sql/populate.sh" # import the test schema files
  - mysql -h127.0.0.1 -uindex_digest -pqwerty index_digest -v -e '\s; SHOW TABLES;'

install: make install
script: make coverage && make lint && make demo

# @see https://github.com/nickstenning/travis-pip-cache/issues/1
cache: pip
