language: python
dist: trusty
python:
  - "2.7"
  #- "3.3"
  - "3.4"
  #- "3.5"
  - "3.6"
services:
  - docker
env:
  # @see https://docs.travis-ci.com/user/environment-variables/#Defining-Multiple-Variables-per-Item
  # @see https://hub.docker.com/_/mysql/
  - DOCKER_IMAGE=mysql:5.5
  - DOCKER_IMAGE=mysql:5.6
  - DOCKER_IMAGE=mysql:5.7
  - DOCKER_IMAGE=mysql:8.0
  # @see https://hub.docker.com/_/mariadb/
  - DOCKER_IMAGE=mariadb:10.0  # used by Wikipedia
  - DOCKER_IMAGE=mariadb:10.2
before_script:
  # @see https://medium.com/@mtparet/install-mysql-server-5-7-on-travis-96f2ebc0f339
  # @see https://hub.docker.com/_/mysql/
  - sudo service mysql stop  # stop any running MySQL server
  - sudo docker run -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d -p 3306:3306 $DOCKER_IMAGE
  - sleep 15 # wait for MySQL server to be fully set up
  - sudo docker ps
  # set up a database
  - mysql --protocol=tcp -u root -e "CREATE DATABASE index_digest; CREATE USER 'index_digest'@'%' IDENTIFIED BY 'qwerty'; GRANT ALL ON index_digest.* TO 'index_digest'@'%';"
  - "./sql/populate.sh" # import the test schema files
  - mysql --protocol=tcp -uindex_digest -pqwerty index_digest -v -e '\s; SHOW TABLES;'

install: make install
script: make coverage && make lint && make demo

# @see https://github.com/nickstenning/travis-pip-cache/issues/1
cache: pip
